### ISSUE TITLE
simulating_gene_trees.jl produces gene tree files with "_1" appended to every taxon

### ISSUE THREAD

**Issue by mbjorner** [mbjorner/hybrid-detection-comparison#2]
this means to use the files n25h5.net, n50h10.net, and n100h20.net that we must alter them to include these "_1" suffixes, or calculating the expected gene trees will be incorrect :(

**Comment by crsl4** [comment]
oh I wonder if this is coming from hybrid lambda! Do we know when the _1 are added?

**Comment by mbjorner** [comment]
it must be! I'm not finding anywhere where the _1's are added, even the rooted network that is created by the process doesn't have the "_1" endings.

**Comment by mbjorner** [comment]
fixed with new simulating-gene-trees.jl additions
